#config application spring-boot
server:
  port: 8082
spring:
  #oracle config connection
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: system
    password: admin1
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
  #mongodb config connection
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/udemydb
